import Footer from "./components/footer/Footer";
import Navbar from "./components/navbar/Navbar";

import { VideoProvider } from "./context/VideoContext";
import "./globals.css";
export const metadata = {
  title: "Let's OutSource",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <VideoProvider>
        <Navbar />
        {children}
        <Footer />
        </VideoProvider>
      </body>
    </html>
  );
}
